### ISSUE TITLE
.sync modifier

### ISSUE THREAD

**Issue by itomtom** [ngVue/ngVue#107]
Hi,

I would just like to ask if the [.sync](https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier) modifier is available or something of the equivalent?

In addition, is it possible to `$emit` from the Vue component to the Angular component with the name of the event containing colon _**:**_ in the name?

**Comment by jaredmcateer** [comment]
Hi @itomtom, modifiers are not supported as far as I can tell\*, currently you'd have to write the binding using the prop/emit method. I'd be happy to accept a PR if you're willing to work on it though. 

It seems like events with colons work I did a test using the example server where I modified `updateFirstName` in index.js to emit `new-first-name:test` and then in the index.html I modified the angular directive to use `v-on-new-first-name:test` and the binding worked.

\* Disclaimer: I'm currently trying to maintain this package but I am not an expert on its code base yet, I'm just another person trying to migrate our legacy angular app to Vue.

**Comment by jaredmcateer** [comment]
I know this is quite late but in trying to figure out Composition API support I was also looking at the code to see if this is something I could add support for and realized that angular [normalizes](https://docs.angularjs.org/guide/directive#normalization) attributes 

e.g.,
`v-on-foo:bar`
`v-on-foo_bar`
`v-on-fooBar`

all get normalized to `vOnFooBar`, which makes it problematic to support colon separated events.

 Vue 3 has also dropped `.sync` and reworked `v-model` to support 2 way bindings. I think if someone were to implement this in ngVue it would be to emulate Vue 3's style by adding a `v-model-<propName>="<boundData>"`
