### ISSUE TITLE
Vue component not rendering on IE 

### ISSUE THREAD

**Issue by shrik15** [ngVue/ngVue#120]
I am using a Vue component. It works fine with chrome browser but on IE it is never rendered.

TypeError: Object doesn't support property or method 'assign'

**Comment by jaredmcateer** [comment]
Internet Explorer doesn't support modern JavaScript. you'll need to [polyfill `Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) and any other missing features.
