### ISSUE TITLE
Plugins do not work with Webpack 5

### ISSUE THREAD

**Issue by sdrioux** [ngVue/ngVue#146]
Webpack 5 now supports the `exports` option in `package.json`.  As a result, we can't import anything except: 

```
    ".": {
      "require": "./build/index.js",
      "import": "./build/index.esm.js"
    }
```

This means we can't do `import 'ngVue/build/plugins.js';` as Webpack gives the error: 

```
Module not found: Error: Package path ./build/plugins.js is not exported from package /Users/silas.rioux/code/priori_legal/node_modules/ngVue (see exports field in /Users/silas.rioux/code/priori_legal/node_modules/ngVue/package.json)
```

Can you please add that plugin.js file as an allowable export?

**Comment by jaredmcateer** [comment]
Sorry for the delayed response @sdrioux I've been really sick. I probably won't get to this until sometime in Jan. If you cannot wait I would gladly accept a PR.

**Comment by sdrioux** [comment]
No worries!  I know what thats like.  I am on Christmas break but if I get a chance I will throw something up.

**Comment by sinh117801** [comment]
Hello, is there any solution or fix manually on for this?

**Comment by jaredmcateer** [comment]
If someone could post a minimal reproducible test case I'll try and make some time this week to fix it.
