### ISSUE TITLE
Error: ngVue components must have a parent tag or they will not render

### ISSUE THREAD

**Issue by maxillosoft-dimitry** [ngVue/ngVue#160]
I keep getting this error and cannot figure out what I am missing.  
Error: ngVue components must have a parent tag or they will not render

Can someone point me where I should look?
 
I found in the code where it happens but I am not sure what it is referring to.
Line 13 in ngVueLinker.js
if (!jqElement.parent().length) throw new Error('ngVue components must have a parent tag or they will not render')

Thanks
-Dimitry

**Comment by jaredmcateer** [comment]
Unclear without an example of your code but the tests should that it happens if you tried to `$compile` the component directly from a new scope with no wrapping element.

```
    it('should throw an error if there is no parent tag', () => {
      expect(() => {
        $compile('<vue-component name="HelloComponent" />')($rootScope.$new())
      }).toThrowErrorMatchingSnapshot()
    })
```
