### ISSUE TITLE
How does event handling work

### ISSUE THREAD

**Issue by FranzSkuffka** [ngVue/ngVue#24]
First off, thank you for this very cool piece of software!

I am kind of stuck on how I would handle a simple click event with ngVue.
I can not find anything about this in the docs.

How is the data flow from the vue component upwards to the angular controller meant to work?

**Comment by nicolaspayot** [comment]
Well, you can't use Vue events from a Vue component that's within an AngularJS one, because you're in AngularJS context. You have to bind event callbacks as props. Here's an example:

- hello.controller.js (AngularJS)
```javascript
class HelloController {
  constructor($scope) {
    this.$scope = $scope;
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    // Don't forget to use $scope.$apply in case you need to update model data
    this.$scope.$apply(() => { ... });
  }
}
```

- hello.html (AngularJS)
```html
<vue-component name="Hello" vprops-on-click="$ctrl.handleClick"></vue-component>
```

- Hello.vue
```html
<script>
export default {
  props: {
    onClick: Function
  },
  ...
  methods: {
    whateverMethod() {
      this.onClick(this.whateverArg);
    }
  }
};
</script>
```

Hope this helps ;-)

**Comment by FranzSkuffka** [comment]
Thank, I will try it out. If I am successful, I will open a PR to merge this intel into the docs!

**Comment by FranzSkuffka** [comment]
Done please review PR.
