### ISSUE TITLE
Omit angular from build

### ISSUE THREAD

**Issue by FranzSkuffka** [ngVue/ngVue#27]
Due to the environment of the SPA I am developing, AngularJS is included per script tag by default.
However, I have no option of including ngVue as script tag.
Is there a way to initialize ngVue using `require` without also importing angular?

Console throws:
```
WARNING: Tried to load angular more than once.
```

**Comment by dorayx** [comment]
>  I have no option of including ngVue as script tag.

You could include ngVue with unpkg:  https://unpkg.com/ngVue/build/index.js (or a mini field version: https://unpkg.com/ngVue/build/index.min.js)

I will update the document :-)

> Is there a way to initialize ngVue using require without also importing angular?

angular is [treated as an external dependence](https://github.com/ngVue/ngVue/blob/master/rollup.config.js#L36) and so it is not bundled with ngVue 

:-)

Could you please provide more info about the issue?

**Comment by dorayx** [comment]
oh i know how to fix it
busy recently but i will figure it out in a few days

**Comment by FranzSkuffka** [comment]
If you note the steps here, maybe I can support you. I am currently migrating a 60k line SPA from ng1 to Vue + Vuex using ngVue :) I would love to contribute.

**Comment by FranzSkuffka** [comment]
I tried including directly from the src dir, but my compiler is dying on the JSX / template part. I could not mange to make the transformers work properly.

**Comment by Jexordexan** [comment]
@FranzSkuffka, Are you using webpack? 

If so, this worked for me in my webpack config:
```
   alias: {
      'vue$': 'vue/dist/vue.esm.js',
      'angular': path.join('node_modules', 'angular')
    },
```

**Comment by FranzSkuffka** [comment]
Yes I am using webpack! I will try this out.

**Comment by Jexordexan** [comment]
I found that fix in this bug: https://github.com/webpack/webpack/issues/2134

**Comment by FranzSkuffka** [comment]
I fixed this by adding this to my webpack config
```
      alias: {
        angular: __dirname + "/vue/angular"
      },
```
and `/vue/angular` contains
```
module.exports = window.angular
```
