### ISSUE TITLE
Issue with webpack and the render method

### ISSUE THREAD

**Issue by jonnycraze** [ngVue/ngVue#34]
Hey there, I'm having an issue getting the vue component to pass in my webpack build, it is currently triggering an Unexpected token error.

Here is the component:
`var VDataList = Vue.component('v-process-list', {
  props: {
    data: String
  },
  render (h) {
    return (
      <div>This is the VueJS Component, data received: {this.data}</div>
    )
  }
})`

I think add this to the app:
`
	.value('VDataList', VDataList);
`

And finally in my directive I invoke the component:
`
<vue-component name="VDataList" vprops="testData"></vue-component>
`

I'm suspicious I'm missing something in my webpack config, any help is greatly appreciated.

**Comment by nicolaspayot** [comment]
Hi! Sorry for the (very very) late answer. Is the issue still occurring?  If so, could you please provide a repo with your code? Thanks

**Comment by jonnycraze** [comment]
We ended up getting it working via another means, I will post up the code this evening. We could not however get the code as written above working however.

**Comment by gregevari** [comment]
I made this work by using `vue-loader` and `vue-template` compiler.  

Now my single page component `HelloComponent.vue` just works.
