### ISSUE TITLE
Parent callback called in the context of Vue child component

### ISSUE THREAD

**Issue by nlitwin** [ngVue/ngVue#40]
### Description

I ran into an issue that I _think_ should be handled by `ngVue`. I have a parent Angular component which passes a function, `close`, to a child Vue component. If the `close` callback is called from within Vue, i.e. from clicking the `p` tag, then the callback is called in the context of Vue, meaning `this` points to the wrong object. When `close` is called from Vue, `this.ReportingService` and `this._modalInstance` are both undefined. Of course, if `close` is called from within Angular, everything is fine.

I was able to temporarily solve this by binding the function to the Angular context with:
`this.close = this.close.bind(this);`

However, it seems like if you're trying to communicate back up to a parent component and calling it's callback, it should be in that parent's context. Would this be something that `ngVue` can take care of? For example, we can look at the props passed from Angular to Vue, and if the prop is of type `Function`, it should be bound to the context from where it was passed.

### Relevant code
Angular Component
```js
class ModalController {
  constructor(ReportingService) {
    this.ReportingService = ReportingService;
  }

  $onInit() {
    // Without this line, the code breaks as described above
    // Since this function is also called in the Vue context, bind to this controller
    this.close = this.close.bind(this);
  }

  close(reason) {
    this.ReportingService.report(`Closing modal for reason: ${reason}`);
    this._modalInstance.dismiss();
  }
}
```

```pug
modal-body(vprops-close-modal="$ctrl.close")
```

Vue Component
```pug
.modal-body
    //- omitted code
    p(@click="onClose('skip this step')") Skip this step
```

```js
export default {
  props: {
    closeModal: Function,
  },
  methods: {
    onClose(reason) {
      this.closeModal(reason);
    },
  },
}
```

**Comment by nicolaspayot** [comment]
Hi! Thanks for the detailed description and code samples ;-)

We're aware of this behaviour. However, I'm not sure this is something ngVue should handle. This happens when using ES6 class only, because JavaScript class methods are not bound by default, as stated here: https://reactjs.org/docs/handling-events.html.

**Comment by nlitwin** [comment]
Thank you for the quick response and link! I'll give the

> experimental public class fields syntax

a try mentioned in the article, which looks to me like just setting the `class` method to an arrow function. Anyway, I think you're right that this isn't something `ngVue` should handle.
