### ISSUE TITLE
Example not running

### ISSUE THREAD

**Issue by MiguelBrito1086** [ngVue/ngVue#46]
Hello,

Trying to figure out how to use ngVue. Cloned and ran npm install but says that there is no script for npm run dev-example and npm run dev... Any suggestions?

/Users/miguelbrito/.npm/_logs/2018-03-15T14_06_02_539Z-debug.log

**Comment by nicolaspayot** [comment]
Hi!

Where do `npm run dev-example` and `npm run dev` come from? ;-)
Only available script to run example is `npm run example`, as defined in `package.json`.

**Comment by MiguelBrito1086** [comment]
Sorry, I was just following this page https://github.com/ngVue/ngVue/tree/master/example... but I will try to npm run example! Thank you so much for the quick response!!

**Comment by nicolaspayot** [comment]
Oh right! Sorry, I forgot we had this documentation. I'll update asap. Thanks for pointing the issue 👍

**Comment by MiguelBrito1086** [comment]
<img width="1440" alt="screen shot 2018-03-15 at 10 26 14 am" src="https://user-images.githubusercontent.com/27711630/37469358-75b72010-283b-11e8-93fb-c1d99adc49d9.png">

**Comment by nicolaspayot** [comment]
Yep, examples are visible at:
- http://localhost:12345/vue-component/
- http://localhost:12345/create-vue-component/
- http://localhost:12345/plugins-filters/

I'll update the doc with these as well...

**Comment by MiguelBrito1086** [comment]
Sorry for the troubles man! Thank you again.
