### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nitinkumarmishra** [ngVue/ngVue#47]
Example defined in `ngVue` repository working fine but not working in fresh angular project. I created a Stackblitz link for futher reference.
https://stackblitz.com/edit/ng-vue

Thanks.

**Comment by nicolaspayot** [comment]
Yes, you need `babel-plugin-transform-vue-jsx` to use jsx with Vue. And I don't know how to do that with StackBlitz. Your example works fine if you replace the jsx code with
```javascript
return createElement('span', `${this.firstName} ${this.lastName}`)
```
Also, `React` dependency is unnecessary.
