### ISSUE TITLE
Updating Angular Controller from vue component

### ISSUE THREAD

**Issue by craig-doyle-uk** [ngVue/ngVue#55]
Is it possible to update the Angular controller from the Vue component? 

I have an Angular controller that receives data from several services before passing them down to the vue component as props using ngVue, I need to then pass data back to the controller after checking for the existence of data within the component. As the props are immutable, and the vue component variables are not available outside of it's template I'm looking for a way to update the scope variable attached to the v-props.

Thanks in advance for any guidance with whether this is possible.

**Comment by dorayx** [comment]
Perhaps it is possible but I have not tested.

In an angular controller you can create a **set** callback to update data and then pass it to a vue component. In the vue component you will use the component hooks to call the received **set** callback from the angular controller with any component data.

**Comment by erickwilder** [comment]
The best approach I came up with to communicate from Vue components back to AngularJS _without polluting Vue components_ and to keep AngularJS changes as minimal as possible was to adopt the _event bus_ pattern.

```
// AngularJS controller/component
import eventBus from './event-bus'

eventBus.$on('Component:changed', doSomething)
```

this was extremely helpful to trigger `ui-router` state transitions _from  Vue components_:

```
import eventBus from './event-bus'
app.run(($state) => {
   eventBus.$on('ng:stateChange', (stateName, params, config) =>{
        $state.go(stateName, params, config)
  })
})
```

**Comment by craig-doyle-uk** [comment]
Thanks for the comments @dorayx @erickwilder . 
I resolved my particular use case in the following way : 

Angular controller

    $scope.showNotification = function (someArg) {
     doSomething
    }

Angular view

    <my-component  vprops-on-update="showNotification"></my-component>

Vue Template

    <div change={this.onUpdate}> ... some content here </div>

Vue Component

    @Component({
     props : {
      onUpdate: Function
     }
    ....
    // controller updated by firing this.$props.onClick(someArg)
