### ISSUE TITLE
Vue dev tools do not pick up the app

### ISSUE THREAD

**Issue by mickeyvip** [ngVue/ngVue#59]
Hello,

I see that the Vue dev tools do not recognise that the Vue app is running.

Am I doing something wrong? Can this be fixed?

Thank you

**Comment by nicolaspayot** [comment]
Hi,

It's a bit hard to diagnose the cause(s) of the problem you encounter with this amount of information. If your Vue component(s) is / are correctly integrated within your AngularJS app and the Vue dev tools are working fine in your browser, you should see your Vue component(s). This is not really related to ngVue.

**Comment by mickeyvip** [comment]
Hi, 

thank you for the quick response and sorry for getting back so late.

The Vue dev tools icons stays grey and says "Vue.js is not detected" - that was got me confused. 

But choosing the "Vue" tab in dev tools does actually show the Vue object. Sometimes I need to reopen the dev tools for it to pick up the Vue app, but it's ok.

In my case the Vue component is not rendered immediately but after going to a specific tab, so that may be the cause.

I am closing the issue.

Thanks again.
