### ISSUE TITLE
Commonjs app, vue undefined

### ISSUE THREAD

**Issue by randyhoulahan** [ngVue/ngVue#62]
If my component imports Vue and references I get the following error seen here:
https://www.cbddev.xyz/test/vue

 Cannot read property 'use' of undefined

Basically, vue is undefined.  What am I missing?

**Comment by nicolaspayot** [comment]
I'm sorry but we need more information to investigate. Also, `ngVue` does not provide `Vue`. If you need `Vue`, you need to explicitly add it to your dependencies.
