### ISSUE TITLE
Crash when Vue component element is not empty

### ISSUE THREAD

**Issue by pkaminski** [ngVue/ngVue#68]
If you try to put any content into a Vue component's element in your Angular template, ngVue crashes [here](https://github.com/ngVue/ngVue/blob/master/src/angular/ngVueLinker.js#L33) because it can't find the `__slot__` reference.

I'm guessing that element content is supposed to be compiled by Angular and passed as a slot value down to the Vue component, but this doesn't appear to be documented and isn't working for me.

**Comment by nicolaspayot** [comment]
Well, slot support within `<vue-component>` is very experimental. I'm thinking about flagging it as deprecated in futur versions. There are a lot of situations where it doesn't work but it should be ok for simple AngularJS content, such as in the unit test [here](https://github.com/ngVue/ngVue/blob/master/src/__tests__/vue-component.test.js#L258), where it works ok.

Can you show some code or a live example?

**Comment by pkaminski** [comment]
Eh, if you're going to deprecate it anyway it's not really worth investigating -- just consider this another vote in favor of killing the feature.  I don't actually need it, I was just surprised when the page crashed due to a typo in my template (some text inside the component element).
