### ISSUE TITLE
Event names cannot contain dashes

### ISSUE THREAD

**Issue by erickwilder** [ngVue/ngVue#78]
Given a vue component that emits an event like this:

```
this.$emit('something-happened')
```

I can't listen to this even with `v-on-something-happened` on a `<vue-component />` tag and all events have to be named without any word separation inside the Vue component:

```
this.$emit('somethinghappened')
```

Expected result:

Be able to use `v-on-something-happpened="fn"` attribute and listen to all Events triggered by the Vue component.

**Comment by pcable** [comment]
I'm also having this issue. The callback in your case is being registered as `somethingHappened` however vue lowercases all event name when its going to call the callback so it never finds it.  I'm trying to create a patch

**Comment by nicolaspayot** [comment]
@erickwilder well, you can listen to `v-on-something-happened` on a `<vue-component>` tag if the event you emit is using camel case syntax:
```javascript
this.$emit('somethingHappened')
```

We can change this behaviour to allow events to be emitted with kebab case syntax, however this would introduce a breaking change.

**Comment by erickwilder** [comment]
The problem is that it goes against Vue's recommendation of aways emitting events in snake-case. In our codebase we try to normalize all events following that convention as well

**Comment by erickwilder** [comment]
By the way. Do we really need to introduce a breaking change? We could simply allow both

**Comment by realmerx** [comment]
Hello, I also hit the same problem and there seems to be a fork with this fixed (did not test this but code seems ok): https://github.com/pcable/ngVue/commit/99748015438d97267a6de0881bcb83476499c3de.

One hacky way to hack around this is to override $emit method when creating vue constructor function:

```
var VueCompConst2 = Vue.extend(Object.assign({}, vueComponent, {
    created: function() {
        this.oldEmit = this.$emit;
        this.$emit = function(eventName) {
            eventName = eventName.split('-').map((p, i) => (i > 0 ? p.charAt(0).toUpperCase() : p.charAt(0)) + p.slice(1)).join('')
            this.oldEmit(eventName);
        }
    }
}));

```

**Comment by nicolaspayot** [comment]
This pull request https://github.com/ngVue/ngVue/pull/83 should fix the issue. Please, feel free to review it 😉
