### ISSUE TITLE
Issue processing props

### ISSUE THREAD

**Issue by jaredmcateer** [ngVue/ngVue#81]
I ran into an interesting issue with the following code:

    <my-vue-comp v-prop-states="ctrl.states"></my-vue-comp>

When trying to load the app the console outputs the error:

```
logger.js:108 2019-03-07T22:40:23.908Z ERROR browser-console [Vue warn]: Missing 
required prop: "states"

found in

---> <Default1> at client/ui-components/MyVueComponent.vue
       <Root>
```

Stepping through the code I found that the reactive data object being passed to the vue instance constructor had a props property named `tates` instead of `states`. I finally noticed my typo that the prop in `v-prop-states` was singular and needed to be plural, but ngVue was parsing it as `vPropsTates`.

**Comment by nicolaspayot** [comment]
Oh wow. Nice catch! Thank you. The PR https://github.com/ngVue/ngVue/pull/82 should fix it. Feel free to review it if you want @jaredmcateer

**Comment by jaredmcateer** [comment]
Thanks, lgtm, it's the sort of problem that once you know about it it's easy to avoid but it was a head scratcher for a few minutes so nice if future devs don't need to stub their foot on it.
