### ISSUE TITLE
Usefulness of $compile for slot

### ISSUE THREAD

**Issue by Lukinoh** [ngVue/ngVue#93]
Hi,

I'm playing with ngVue and I am trying to understand why we need to do a `$compile` in the `rootProps.mounted` in the `ngVueLinker` function. 

Concretely, I have a vue component `MyComponent` with a slot. The content of the slot contains some `ng-if``s.

```html
  <MyComponent>
    <span>
      <div ng-if="true">TRUE</div>
      <div ng-if="false">FALSE</div>
      <div ng-if="true">TRUE</div>
      <button ng-click="vm.onClick()">Click me!</button>
    </span>
  </MyComponent>
```

With the $compile used the `ng-if`s are not displayed (line 177, https://jsfiddle.net/6jnL9sua/2/)
Without the $compiler used the `ng-if`s are displayed (line 178, https://jsfiddle.net/6jnL9sua/3/)
Same behaviour happen with `ng-repeat`.

If I put a angular component inside the slot, the component is rendered with and without the $compile. If the component has some `ng-if` or `ng-repeat` inside they are interpreted either way.

```
  <MyComponent>
    <span>
      <ng-my-awesome-component></ng-my-awesome-component>
    </span>
  </MyComponent>
```

So concretely, I don't understand in which case the $compile is useful.

Thank you

P.S. Thank korya for the JSFiddle :p
P.S. Don't hesitate to change the title of the issue if it is not meaningful

**Comment by nicolaspayot** [comment]
Hi! Sorry for the late answer. Well, I think you're totally right... It looks like `jqElement[0].children` returns an HTMLCollection of "compiled" nodes. Please, feel free to throw a PR!
