### ISSUE TITLE
Deprecation warning for camelCase event names cannot be suppressed

### ISSUE THREAD

**Issue by scottmmjackson** [ngVue/ngVue#94]
https://github.com/ngVue/ngVue/blob/bb89707ae1d9fc81d0405676ab1140cd15a1c22b/src/index.js#L63

This warning was introduced in #83 - however, it cannot be suppressed. 

A common pattern is to use NodeJS-style environment variables which can be configured in webpack:
 
```
if (process && process.env && process.env.NODE_ENV === 'development'`) {
   logger.warn('Be sure to do these things before this project is shipped')
} else {
   // be silent
}
```

https://webpack.js.org/plugins/environment-plugin/

Reproduce:

(1) Include ngVue in a productionized project, either using a `<script>` tag or importing using ES6 modules.

Expected:

- No deprecation warning occurs merely by including the code

Actual:

- Deprecation warning occurs merely by including the code.

**Comment by scottmmjackson** [comment]
Oh, no, I see what's going on.

`process.env.BABEL_ENV === 'test'` is where it's suppressed. Though, that may be targeting the `ngVue` tests themselves, and not library consumers?

**Comment by nicolaspayot** [comment]
@scottmmjackson yes you're totally right! Thanks for the PR. I'll review it right away.

**Comment by jaredmcateer** [comment]
How long are you planning on keeping this deprecation warning in ngVue? It currently spamming the heck out of our tests even though we don't have any camelCase event names.

![Screenshot from 2019-05-16 13-32-53](https://user-images.githubusercontent.com/781540/57881799-6d7f9180-77df-11e9-8a4d-11e926f5c626.png)

**Comment by scottmmjackson** [comment]
@jaredmcateer If you're using babel, set [BABEL_ENV=test](https://new.babeljs.io/docs/en/next/babelrc.html#env-environment-option). Same with webpack, but in a [different way](https://webpack.js.org/plugins/environment-plugin/).

Yeah, it's a bit jarring, but there's a workaround here.

**Comment by jaredmcateer** [comment]
Ah I see the problem, I assumed that BABEL_ENV was just some alias/polyfill for variables like NODE_ENV when using Babel, but I actually have to set `BABEL_ENV=test` in my env variables even we don't use it.
